trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  PYTHON_VERSION: "3.10"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(PYTHON_VERSION)"
    displayName: "Use Python $(PYTHON_VERSION)"

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest requests-mock
    displayName: "Install dependencies"

  - script: |
      echo "##[section]Setting PYTHONPATH to repo root"
      export PYTHONPATH=$(Build.SourcesDirectory)
      pytest -q
    displayName: "Run unit tests"
